# Install mongodb
---
- name: Import the public key used by the package management system
  sudo: yes
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4

- name: Create a list file for MongoDB
  sudo: yes
  lineinfile: >
    line="deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/4.0 multiverse"
    dest=/etc/apt/sources.list.d/mongodb-org-4.0.list
    state=present
    create=yes

- name: Install mongo org server
  sudo: yes
  apt: name=mongodb-org-server state=latest update_cache=yes

- name: Install mongo
  sudo: yes
  apt: name=mongodb-org state=latest update_cache=yes
