#
---
- name: SES1 Ansible Practice
  hosts: 'all'
  remote_user: 'root'
  gather_facts: no
  pre_tasks:
    - name: apt-get update
      raw: apt-get update -qq
    - name: install python 2.7 and aptitude
      raw: apt-get install -qq python2.7 aptitude
    - name: set python 2.7 as default
      raw: update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
  roles:
    - common
    - nginx
    - rails_api_user
    - ruby
